version: "3"
services:
  webserver:
    image: abiosoft/caddy:0.10.10
    ports:
      - "80:80"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./certs:/root/.caddy"
  app:
    build: ./app
    container_name: app.webapp
    volumes:
      - "./app:/src"
  ui:
    build: ./ui
    container_name: ui.webapp
    volumes:
      - "./ui/src:/src/src"
  postgres:
    image: postgres:10.1
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: crypto
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
